require 'open-uri'

eval(open('https://gist.githubusercontent.com/rcobelli/efd294050bc98d58d2b43fdf279b9eb2/raw/snapTemplate.rb').read)

app_identifier "com.rybel-llc.frame-counter"
scheme "FrameTime"
