require 'open-uri'

eval(open('https://gist.githubusercontent.com/rcobelli/efd294050bc98d58d2b43fdf279b9eb2/raw/58b73a10c50c278f082bf4aaee44046a4cc13d8e/snapTemplate.rb').read)

app_identifier "com.rybel-llc.frame-counter"
scheme "FrameTime"
